/**
 * car-part-core openapi spec
 *
 * Contact: blabla@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CarManufacturerResponse { 
    /**
     * identifier of the car manufacturer
     */
    id: string;
    /**
     * name of the car manufacturer
     */
    name: string;
}

