/**
 * car-part-core openapi spec
 *
 * Contact: blabla@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Allowed currency
 */
export type Currency = 'RON' | 'EUR' | 'USD';

export const Currency = {
    Ron: 'RON' as Currency,
    Eur: 'EUR' as Currency,
    Usd: 'USD' as Currency
};

