/**
 * car-part-core openapi spec
 *
 * Contact: blabla@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Allowed currency
 */
export enum Currency {
    Ron = 'RON',
    Eur = 'EUR',
    Usd = 'USD'
}

