image: docker:latest
services:
  - docker:dind

stages:
  - build-stage
  - test-stage
  - build-docker-image

build app:
  stage: build-stage
  image: eclipse-temurin:21-jdk-alpine-3.21
  artifacts:
    paths:
      - ./car-part-core-micro/target/*.jar
  script:
    - cd car-part-core-micro
    - chmod +x mvnw
    - ./mvnw package -DskipTests

test:
  stage: test-stage
  image: eclipse-temurin:21-jdk-alpine-3.21
  script:
    - cd car-part-core-micro
    - chmod +x mvnw
    - ./mvnw test
build docker image:
  stage: build-docker-image
  script:
    - cd ./car-part-core-micro
    - docker build -t registry.gitlab.com/car-app/car-part-core-micro$CI_PIPELINE_IID .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push registry.gitlab.com/car-app/car-part-core-micro$CI_PIPELINE_IID





