image: docker:latest
services:
  - docker:dind

stages:
  - build-stage
  - test-stage
  - build-docker-image

build app:
  stage: build-stage
  image: eclipse-temurin:21-jdk-alpine-3.21
  artifacts:
    paths:
      - ./target/*.jar
  script:
    - ./mvnw package -DskipTests

test:
  stage: test-stage
  image: eclipse-temurin:21-jdk-alpine-3.21
  script:
    - ./mvnw test
