server:
  port: 9091

management:
  server:
    port: 9091
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true

spring:
  application:
    name: car-part-front-micro

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: front-micro
            client-secret:
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            user-name-attribute: preferred_username
            authorization-uri: http://${KEYCLOAK_URI}/realms/GINI/protocol/openid-connect/auth
            token-uri: http://${INTERNAL_KEYCLOAK_URI}:8080/realms/GINI/protocol/openid-connect/token
#            user-info-uri: http://${INTERNAL_KEYCLOAK_URI}:${INTERNAL_KEYCLOAK_PORT}/realms/GINI/protocol/openid-connect/userinfo
            jwk-set-uri: http://${INTERNAL_KEYCLOAK_URI}:${INTERNAL_KEYCLOAK_PORT}/realms/GINI/protocol/openid-connect/certs

  web:
    resources:
      static-locations: classpath:/static/browser, classpath:/templates/login

  thymeleaf:
    prefix: classpath:/templates/

core:
  micro-url:

logging:
  level:
    org:
      springframework: DEBUG
#        security: DEBUG
#        web: DEBUG
#        cloud: DEBUG
