/**
 * car-part-core openapi spec
 *
 * Contact: blabla@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PriceResponse } from './priceResponse';


export interface AfPartResponse { 
    id?: string;
    afPartNumber?: string;
    price?: PriceResponse;
}

