/**
 * car-part-core openapi spec
 *
 * Contact: blabla@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CarRequest { 
    /**
     * car model name
     */
    model: string;
    /**
     * the year when the production of the model started
     */
    productionStartYear: string;
    /**
     * the year when the production of the model ended
     */
    productionEndYear: string;
    /**
     * car manufacturer id from database
     */
    carManufacturerId: string;
}

