/**
 * car-part-core openapi spec
 *
 * Contact: blabla@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PriceRequest } from './priceRequest';


export interface PartRequest { 
    name: string;
    /**
     * identification number of the part
     */
    partNumber: string;
    carId: string;
    manufacturerId: string;
    price: PriceRequest;
}

