/**
 * car-part-core openapi spec
 *
 * Contact: blabla@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AfPartFilterResponse } from './afPartFilterResponse';
import { PriceResponse } from './priceResponse';


export interface PartFilterResponse { 
    id: string;
    name: string;
    afParts?: Array<AfPartFilterResponse>;
    price?: PriceResponse;
}

